# Generated by Django 5.1.4 on 2025-01-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_transaction_id_shippinginformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinginformation',
            old_name='zipCode',
            new_name='zipcode',
        ),
    ]
