# Generated by Django 5.1.4 on 2025-01-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
